/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AButton: typeof import('antd')['Button']
  const AForm: typeof import('antd')['Form']
  const AInput: typeof import('antd')['Input']
  const ATag: typeof import('antd')['Tag']
}
