/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AButton: typeof import('antd')['Button']
  const error: typeof import('./src/view/error/index')['default']
  const login: typeof import('./src/view/login/index')['default']
  const main: typeof import('./src/view/main/index')['default']
}
